from src.answer.educate.helpers import *
from src.answer.educate.handlers import (
    EducateExecutePlans,
    EducateGetEvents,
    EducateGetPlans,
    EducateGetTargetAward,
    EducateUpgradeFavor,
    EducateTriggerEnd,
    EducateGetEndings,
    EducateSetTarget,
    EducateSubmitTask,
    EducateSetCall,
    EducateAddTaskProgress,
    EducateAddExtraAttr,
    ChangeEducateCharacter,
    EducateMapSiteOperate,
    EducateRefresh,
    EducateRequest,
    EducateRequestOption,
    EducateRequestShopData,
    EducateReset,
    EducateShopping,
    EducateTriggerEvent,
    EducateTriggerSpecEvent,
)
from src.answer.educate.exports import (
    EducateFlagID,
    HasEducateFlag,
)

__all__ = [
    # constants
    "educateResultOK", "educateResultFailed",
    "educateFlagHomeEventBase", "educateFlagSpecialEventBase",
    "educateFlagDiscountBase", "educateFlagTargetAwardBase",
    "educateUnsupportedTypeResult", "educatePlanValidationFailedResult",
    "legacyEducateResultOK", "legacyEducateResultFailure",
    "legacyEducateCallNameMin", "legacyEducateCallNameMax",
    "childSiteCategory", "childSiteOptionCategory",
    "childSiteOptionBranchCategory", "childTaskCategory",
    "childTargetSetCategory", "childDataCategory",
    "childEndingCategory", "secretarySpecialShipCategory",
    "educateLegacyCategory",
    # config structs
    "educateSpecialEventConfig", "educateEventConfig",
    "educateShopConfig", "educateShopTemplateConfig",
    "educateTargetSetConfig", "educateTaskConfig",
    "educateSiteConfig",
    "legacyChildSite", "legacyChildSiteOption",
    "legacyChildTask", "legacyChildTargetSet",
    "legacyChildData", "legacySecretarySpecialShip",
    "EducateShopGoodsState", "EducateShopState",
    # config loaders
    "load_educate_special_events", "load_educate_events",
    "load_educate_shop_configs", "load_educate_target_and_task_configs",
    "load_educate_site_options", "default_educate_site_options",
    "load_legacy_config_by_id", "legacy_config_exists",
    "load_legacy_child_data", "legacy_site_has_option",
    # helpers
    "has_educate_flag", "set_educate_flag",
    "to_child_drop", "apply_educate_child_drop",
    "choose_educate_target_id", "shop_goods_from_config",
    "shop_refresh_key", "ensure_educate_shop_state",
    "populate_educate_snapshot",
    "is_valid_legacy_call_name", "build_legacy_child_drop",
    "get_or_create_legacy_educate_state", "save_legacy_educate_state",
    "bool_to_uint32", "append_unique_uint32", "contains_uint32",
    "parse_any_uint32", "educate_flag_id",
    # exports
    "EducateFlagID", "HasEducateFlag",
    # handlers
    "EducateExecutePlans", "EducateGetEvents", "EducateGetPlans",
    "EducateGetTargetAward", "EducateUpgradeFavor", "EducateTriggerEnd",
    "EducateGetEndings", "EducateSetTarget", "EducateSubmitTask",
    "EducateSetCall", "EducateAddTaskProgress", "EducateAddExtraAttr",
    "ChangeEducateCharacter", "EducateMapSiteOperate", "EducateRefresh",
    "EducateRequest", "EducateRequestOption", "EducateRequestShopData",
    "EducateReset", "EducateShopping", "EducateTriggerEvent",
    "EducateTriggerSpecEvent",
]
