CREATE TABLE IF NOT EXISTS commanders (
  commander_id bigint PRIMARY KEY,
  account_id bigint NOT NULL,
  level integer NOT NULL DEFAULT 1,
  exp integer NOT NULL DEFAULT 0,
  name text NOT NULL,
  last_login timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  guide_index bigint NOT NULL DEFAULT 0,
  new_guide_index bigint NOT NULL DEFAULT 0,
  name_change_cooldown timestamptz NOT NULL DEFAULT '1970-01-01 00:00:00+00',
  room_id bigint NOT NULL DEFAULT 0,
  exchange_count bigint NOT NULL DEFAULT 0,
  draw_count1 bigint NOT NULL DEFAULT 0,
  draw_count10 bigint NOT NULL DEFAULT 0,
  support_requisition_count bigint NOT NULL DEFAULT 0,
  support_requisition_month bigint NOT NULL DEFAULT 0,
  collect_attack_count bigint NOT NULL DEFAULT 0,
  acc_pay_lv bigint NOT NULL DEFAULT 0,
  living_area_cover_id bigint NOT NULL DEFAULT 0,
  selected_icon_frame_id bigint NOT NULL DEFAULT 0,
  selected_chat_frame_id bigint NOT NULL DEFAULT 0,
  selected_battle_ui_id bigint NOT NULL DEFAULT 0,
  display_icon_id bigint NOT NULL DEFAULT 0,
  display_skin_id bigint NOT NULL DEFAULT 0,
  display_icon_theme_id bigint NOT NULL DEFAULT 0,
  manifesto text NOT NULL DEFAULT '',
  dorm_name text NOT NULL DEFAULT '',
  random_ship_mode bigint NOT NULL DEFAULT 0,
  random_flag_ship_enabled boolean NOT NULL DEFAULT false,
  ship_bag_size bigint NOT NULL DEFAULT 0,
  equip_bag_size bigint NOT NULL DEFAULT 0,
  commander_bag_size bigint NOT NULL DEFAULT 0,
  spweapon_bag_size bigint NOT NULL DEFAULT 0,
  tactical_class_slots bigint NOT NULL DEFAULT 2,
  loading_pic_open_flag BIGINT NOT NULL DEFAULT 0,
  loading_pic_id_list_1 BIGINT[] NOT NULL DEFAULT '{}',
  loading_pic_id_list_2 BIGINT[] NOT NULL DEFAULT '{}',
  deleted_at timestamptz,
  child_display bigint NOT NULL DEFAULT 1004,
  mail_storeroom_lv bigint NOT NULL DEFAULT 1,
  secretary_affinity_last_ts timestamptz,
  secretary_affinity_interval_min integer NOT NULL DEFAULT 310
);
