CREATE TABLE IF NOT EXISTS owned_ships (
  owner_id bigint NOT NULL REFERENCES commanders(commander_id) ON DELETE CASCADE,
  ship_id bigint NOT NULL REFERENCES ships(template_id) ON DELETE CASCADE,
  id bigserial PRIMARY KEY,
  level bigint NOT NULL DEFAULT 1,
  exp bigint NOT NULL DEFAULT 0,
  surplus_exp bigint NOT NULL DEFAULT 0,
  max_level bigint NOT NULL DEFAULT 50,
  intimacy bigint NOT NULL DEFAULT 5000,
  is_locked boolean NOT NULL DEFAULT false,
  propose boolean NOT NULL DEFAULT false,
  common_flag boolean NOT NULL DEFAULT false,
  blueprint_flag boolean NOT NULL DEFAULT false,
  proficiency boolean NOT NULL DEFAULT false,
  activity_npc bigint NOT NULL DEFAULT 0,
  custom_name text NOT NULL DEFAULT '',
  change_name_timestamp timestamptz NOT NULL DEFAULT '1970-01-01 01:00:00+00',
  create_time timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  energy bigint NOT NULL DEFAULT 150,
  state bigint NOT NULL DEFAULT 0,
  state_info1 bigint NOT NULL DEFAULT 0,
  state_info2 bigint NOT NULL DEFAULT 0,
  state_info3 bigint NOT NULL DEFAULT 0,
  state_info4 bigint NOT NULL DEFAULT 0,
  skin_id bigint NOT NULL DEFAULT 0,
  is_secretary boolean NOT NULL DEFAULT false,
  secretary_position bigint,
  secretary_phantom_id bigint NOT NULL DEFAULT 0,
  deleted_at timestamptz
);
