CREATE TABLE IF NOT EXISTS skins (
  id bigint PRIMARY KEY,
  name text NOT NULL,
  ship_group bigint NOT NULL,
  "desc" text,
  bg text,
  bg_sp text,
  bgm text,
  painting text,
  prefab text,
  change_skin jsonb,
  show_skin text,
  skeleton_skin text,
  ship_l2_d_id jsonb,
  l2_d_animations jsonb,
  l2_d_drag_rate jsonb,
  l2_d_para_range jsonb,
  l2_dse jsonb,
  l2_d_voice_calib jsonb,
  part_scale text,
  main_ui_fx text,
  spine_offset jsonb,
  spine_profile jsonb,
  tag jsonb,
  time jsonb,
  get_showing jsonb,
  purchase_offset jsonb,
  shop_offset jsonb,
  rarity_bg text,
  special_effects jsonb,
  group_index integer,
  gyro integer,
  hand_id integer,
  illustrator integer,
  illustrator2 integer,
  voice_actor integer,
  voice_actor2 integer,
  double_char integer,
  lip_smoothing integer,
  lip_sync_gain integer,
  l2_d_ignore_drag integer,
  skin_type integer,
  shop_id integer,
  shop_type_id integer,
  shop_dynamic_hx integer,
  spine_action jsonb,
  spine_use_live2_d integer,
  live2_d_offset jsonb,
  live2_d_profile jsonb,
  fx_container jsonb,
  bound_bone jsonb,
  smoke jsonb
);
