CREATE TABLE IF NOT EXISTS weapons (
  id bigint PRIMARY KEY,
  action_index text NOT NULL,
  aim_type integer NOT NULL,
  angle integer NOT NULL,
  attack_attribute integer NOT NULL,
  attack_attribute_ratio integer NOT NULL,
  auto_aftercast jsonb,
  axis_angle integer NOT NULL,
  barrage_id jsonb,
  bullet_id jsonb,
  charge_param jsonb,
  corrected integer NOT NULL,
  damage integer NOT NULL,
  effect_move integer NOT NULL,
  expose integer NOT NULL,
  fire_fx text,
  fire_fx_loop_type integer NOT NULL,
  fire_sfx text,
  initial_over_heat integer NOT NULL,
  min_range integer NOT NULL,
  oxy_type jsonb,
  precast_param jsonb,
  queue integer NOT NULL,
  range integer NOT NULL,
  recover_time jsonb,
  reload_max integer NOT NULL,
  search_condition jsonb,
  search_type integer NOT NULL,
  shake_screen integer NOT NULL,
  spawn_bound jsonb,
  suppress integer NOT NULL,
  torpedo_ammo integer NOT NULL,
  type integer NOT NULL
);
